# Generated by Django 5.1.5 on 2025-02-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customerordersview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrdersView',
        ),
    ]
